### ISSUE TITLE
最后一步提示  throw SyntaxError("尝试关闭不存在的“{}”。");

### ISSUE THREAD

**Issue by huanzhiyi** [NXY666/Jsjiemi#58]
### 操作系统

Windows

### Node.js 版本号

v16.14.0

### 问题详情

最后格式化报错

### 目标代码

```JavaScript
https://analysisplay.bearses.com/player/js/artplayer.js
```

**Comment by NXY666** [comment]
这个js用到了很多新东西比如说class，不光是最后一步报错，前面的解密效果也非常不好，我得找个时间专门看看。

**Comment by huanzhiyi** [comment]
感谢您的来信！

**Comment by qcxf8s** [comment]
操作系统
Windows 10

Node.js 版本号
v16.17.0

问题详情
解密函数识别失

目标代码
https://www.lanzou.com/ip1Me0dmjfid

**Comment by NXY666** [comment]
> 好的 只会反馈表层信息，里层的就不懂了
> 
> ---原始邮件---
> 发件人: ***@***.***&gt;
> 发送时间: 2022年9月24日(周六) 下午5:44
> 收件人: ***@***.***&gt;;
> 抄送: ***@***.******@***.***&gt;;
> 主题: Re: [NXY666/Jsjiemi] 最后一步提示  throw SyntaxError("尝试关闭不存在的“{}”。"); (Issue #58)
> 
> 
> 
> 
>  
> 这个js用到了很多新东西比如说class，不光是最后一步报错，前面的解密效果也非常不好，我得找个时间专门看看。
>  
> —
> Reply to this email directly, view it on GitHub, or unsubscribe.
> You are receiving this because you authored the thread.Message ID: ***@***.***&gt;

我已经修复一部分了。

最近学校事特别多，所以还没修好，得等我这段时间忙完了才有时间看😔

**Comment by huanzhiyi** [comment]
> > 好的 只会反馈表层信息，里层的就不懂了
> 
> 我已经修复一部分了。
> 
> 最近学校事特别多，所以还没修好，得等我这段时间忙完了才有时间看😔

嗯，不用急 先忙主要的 旧版本还是能用上，能修复就更好 期待

**Comment by NXY666** [comment]
报错的问题基本上确定了。
是case用{}包围后在大括号外面使用break导致的，我真的没想到还可以这样写😂
```JavaScript
case 'xxx': {
}
break;
case 'xxx': {
}
```
还有其他比如不支持class之类的问题也正在尝试修复。

**Comment by huanzhiyi** [comment]
感谢您的来信！

**Comment by huanzhiyi** [comment]
> 报错的问题基本上确定了。 是case用{}包围后在大括号外面使用break导致的，我真的没想到还可以这样写😂
> 
> ```js
> case 'xxx': {
> }
> break;
> case 'xxx': {
> }
> ```
> 
> 还有其他比如不支持class之类的问题也正在尝试修复。

厉害！期待项目越来越好

**Comment by NXY666** [comment]
新版本已推送，虽然效果仍然不是很好，但至少不会报错了😂
之后我会继续优化的。
