### ISSUE TITLE
【警告】解密函数识别失败

### ISSUE THREAD

**Issue by qcxf8s** [NXY666/Jsjiemi#59]
### 操作系统

Windows

### Node.js 版本号

v16.17.0

### 问题详情

解密函数识别失败

### 目标代码

```JavaScript
https://www.lanzou.com/ip1Me0dmjfid
```

**Comment by echo094** [comment]
这个脚本用的**Obfuscator**混淆，不是**JS加密器**混淆。

**Comment by NXY666** [comment]
目前只支持**一个加密器**，这样描述只是因为某些特殊原因。

**Comment by NXY666** [comment]
最近非常忙，之后可能会多支持点。

**Comment by qcxf8s** [comment]
好的，感谢大佬🤟，期待下个版本！

**Comment by NXY666** [comment]
我看了一下，这个脚本只是经过混淆了，而不是被加密了，所以是不需要解密的。
