### ISSUE TITLE
解密卡在解除代码加密

### ISSUE THREAD

**Issue by wanan99** [NXY666/Jsjiemi#61]
### 操作系统

Windows

### Node.js 版本号

16.16.0

### 问题详情

解密卡在解除代码加密不动，不知道是不是加密文件太大的问题

### 目标代码

```JavaScript
https://wwb.lanzouv.com/i0uq70ggok7e
```

**Comment by NXY666** [comment]
理论上不存在死循环的情况，大概率是文件太大，你可以试着等久一点，我找个时间试试。

**Comment by s-svip** [comment]
等了半小时没反应，老哥你这边有空看看

**Comment by NXY666** [comment]
> 等了半小时没反应，老哥你这边有空看看

好的，我最近手肿了，还有项目在做，有空了我瞧瞧。

**Comment by NXY666** [comment]
我花了10分钟就解密完成了，效果也还可以的。
![image](https://user-images.githubusercontent.com/62371554/204090804-a05be7b9-a670-4a79-b5ac-2dbf2013be94.png)

**Comment by wanan99** [comment]
我是win11不知道跟系统有没有关系

**Comment by NXY666** [comment]
> 我是win11不知道跟系统有没有关系

我也是win11来着

**Comment by NXY666** [comment]
这可能是设备性能或某些不明因素导致的，你还可以检查一下一开始运行时显示的那些路径什么的有没有问题。
