### ISSUE TITLE
前面发了建议了   报错

### ISSUE THREAD

**Issue by hakdwhj** [NXY666/Jsjiemi#64]
### 操作系统

Windows

### 问题详情

![图片](https://user-images.githubusercontent.com/99743445/204512664-2c8b7f30-5344-41c3-afe6-4fcd3f57c40a.png)

### 目标代码

```JavaScript
https://gist.github.com/hakdwhj/a4616177a978e62dd38c962f291b7c7a
```

**Comment by NXY666** [comment]
问题找到了，是正则表达式解析错误的问题，emm我在想办法解决。

**Comment by hakdwhj** [comment]
> 问题找到了，是正则表达式解析错误的问题，emm我在想办法解决。

好的 大佬

**Comment by NXY666** [comment]
问题已修复，可以下载新版本后再试。
