### ISSUE TITLE
解密函数识别失败

### ISSUE THREAD

**Issue by qing52** [NXY666/Jsjiemi#65]
### 操作系统

Windows

### Node.js 版本号

v16.17.1

### 问题详情

<img width="731" alt="1671186545736" src="https://user-images.githubusercontent.com/66190456/208078811-e8bfe6a5-c978-457e-9821-185dd43913a2.png">

### 目标代码

```JavaScript
https://gitee.com/kyxdh/ziyong/raw/master/target.js
```

**Comment by NXY666** [comment]
解密器只支持解密某几个特定的加密器加密的脚本，这个加密我没有见过，所以现在不支持。

**Comment by NXY666** [comment]
这个加密非常复杂，要一键解密非常困难，同时也缺少样本，所以不太可能兼容这种加密。
