### ISSUE TITLE
v6会同时支持v5吗？那就太好用了

### ISSUE THREAD

**Issue by dzdzdzd123** [NXY666/Jsjiemi#68]
### 建议详情

v6会同时支持v5吗？那就太好用了

**Comment by NXY666** [comment]
现在还不支持，今后可能会尝试兼容的。

**Comment by NXY666** [comment]
已推送新版本，由于几乎没有测试样本，识别可能容错率很低。如遇解密失败的情况，欢迎提交issue

**Comment by chenzaichun** [comment]
V5 好象不支持解密，比如这个。
[bbb.js.zip](https://github.com/NXY666/Jsjiemi/files/11257088/bbb.js.zip)

**Comment by NXY666** [comment]
> V5 好象不支持解密，比如这个。
> [bbb.js.zip](https://github.com/NXY666/Jsjiemi/files/11257088/bbb.js.zip)
> 
> 

最近在折腾课设，还有一些别的项目，最近可能都没法弄这玩意😂，之后有时间我再看看。
