### ISSUE TITLE
是否会支持V7？

### ISSUE THREAD

**Issue by richcn** [NXY666/Jsjiemi#70]
### 建议详情

请问后续会支持v7版本么？

**Comment by echo094** [comment]
V7的主要变化在于全局加密函数：

1. 不是固定在代码开头了
2. 在子作用域会使用别名表示全局函数，需要递归还原

感觉是参考了Obfuscator。

**Comment by NXY666** [comment]
目前有一些想法，还在测试可行性。
有点复杂，可能需要很长的时间。
如果测试效果不好，可能也不会做出来。

**Comment by whxntm1** [comment]
期待发布V7的解密脚本

**Comment by YXCQU** [comment]
nb，不是说那个人发律师函嘛，哈哈哈

**Comment by NXY666** [comment]
> nb，不是说那个人发律师函嘛，哈哈哈

之前他说我针对他。但是现在我打算做通用的，不做专门解密某个加密器的工具。

**Comment by wY1k** [comment]
期待进展

**Comment by msechen** [comment]
> 
断人财路犹如杀人父母，难怪他说你针对他

**Comment by NXY666** [comment]
> 断人财路犹如杀人父母，难怪他说你针对他

主要是v6破解太简单了啊，还吹的那么夸张，信的人不都被坑了吗😓
（草，刚刚居然点到编辑评论了，我就说怎么怪怪的）

**Comment by NXY666** [comment]
用现在的方法，想搜索出用法然后进行改动还是太困难了，而且完全没必要。

之后我可能会考虑新开一个仓库，用一些已经有的轮子来做。
