### ISSUE TITLE
建议更改README

### ISSUE THREAD

**Issue by Workear34** [NXY666/Jsjiemi#72]
### 建议详情

“本工具仅作学习交流使用，请务必遵守开源协议，不得用于非法或商业用途。”
建议将这段话加粗并去掉后面的黄豆
“解密文件中必须有且仅有通过某些特定的加密器加密的JavaScript代码（允许经过简单的格式化）”
这句话感觉不太通顺，建议改改

**Comment by NXY666** [comment]
流汗黄豆是我对不遵守开源协议和用于商业用途的直观感受。
整句加粗的话不太好看，我会考虑在重点部分加粗。

呃，至于那句话，我实在不知道怎么表达😂

**Comment by Workear34** [comment]
> 流汗黄豆是我对不遵守开源协议和用于商业用途的直观感受。 整句加粗的话不太好看，我会考虑在重点部分加粗。
> 
> 呃，至于那句话，我实在不知道怎么表达😂

另外我建议在脚本面前也加上“本工具仅作学习交流使用，请务必遵守AGPL3.0开源协议，不得用于非法或商业用途。”

**Comment by NXY666** [comment]
![image](https://user-images.githubusercontent.com/62371554/216758763-b0afa5df-f037-4cee-bc79-faed455722ef.png)
![image](https://user-images.githubusercontent.com/62371554/216758769-50a34caf-a801-4774-8500-3fba1b367479.png)
改好了，会和下个版本一起发布。最近有项目暂时没时间。
