### ISSUE TITLE
解密函数识别失败

### ISSUE THREAD

**Issue by jacylouis** [NXY666/Jsjiemi#76]
### 操作系统

Windows

### Node.js 版本号

v18.15.0

### 问题详情

解密函数识别失败:
![解密函数失败](https://user-images.githubusercontent.com/11785884/224309061-ae083922-f53d-4112-8e5f-c86f17859eed.png)

目标文件:
[extension.zip](https://github.com/NXY666/Jsjiemi/files/10941704/extension.zip)

### 目标代码

```JavaScript
目标文件:
(https://github.com/NXY666/Jsjiemi/files/10941704/extension.zip)
```

**Comment by NXY666** [comment]
我最近很忙，开发已经暂停了。

大概1-2个星期后会有时间看一下。

**Comment by jacylouis** [comment]
没事,你先忙

**Comment by wY1k** [comment]
> 我最近很忙，开发已经暂停了。
> 
> 大概1-2个星期后会有时间看一下。

v7暂时没希望了吗

**Comment by NXY666** [comment]
这个加密非常复杂，要一键解密非常困难，同时也缺少样本，所以不太可能兼容这种加密。
