### ISSUE TITLE
大佬，能帮忙看看这个吗？

### ISSUE THREAD

**Issue by xuexu** [NXY666/Jsjiemi#82]
### 操作系统

Windows

### Node.js 版本号

17.5.0

### 问题详情

解密函数识别失败，可在 GitHub[https://github.com/NXY666/Jsjiemi] 上提交 issue 以寻找原因。

### 目标代码

```JavaScript
https://github.com/leafTheFish/DeathNote/raw/main/chinaTelecom_exchange.js
```

**Comment by NXY666** [comment]
这个加密比较复杂，按照现在的加密方法很难兼容 :(
