### ISSUE TITLE
jiamiv7可以解开吗？

### ISSUE THREAD

**Issue by zzw2016** [NXY666/Jsjiemi#87]
### 建议详情

 解除全局加密 [==========                                        ]
【警告】解密函数识别失败，可在 GitHub[https://github.com/NXY666/Jsjiemi] 上提交 issue 以寻找原因。
[请按任意键继续]

**Comment by NXY666** [comment]
这个项目使用的解密原理限制了它，它无法支持这个加密方式。

**Comment by danceking** [comment]
v6有一个加强版本如何传给你分析呢？大神！
