### ISSUE TITLE
jsjiami.com.v7不支持

### ISSUE THREAD

**Issue by oopsAI9527** [NXY666/Jsjiemi#92]
### 建议详情

jsjiami.com.v7运行时提示【警告】解密函数识别失败，该加密方式可能暂未兼容。这个问题能解决下吗

**Comment by NXY666** [comment]
正则匹配注定了它不能解密比较复杂的加密方法。它只能解密一些使用没有安全性（观赏性很强，很唬人但是没用）的加密器加密的文件。
