### ISSUE TITLE
运行时报错

### ISSUE THREAD

**Issue by roymecat** [NXY666/Jsjiemi#95]
### 操作系统

Linux

### Node.js 版本号

12.22.9

### 问题详情

如图
![Screenshot_2023-07-23-19-53-13-50_84d3000e3f4017145260f7618db1d683](https://github.com/NXY666/Jsjiemi/assets/89294995/29c03de2-38ab-4cac-b7bf-ceec075d9be2)

### 目标代码

```JavaScript
readme里的实例
```

**Comment by NXY666** [comment]
你需要用更新版本的nodejs，解密器使用了比较新的语法。
还有就是&mdash;&mdash;readme里面的实例并不是完整的脚本，是不能直接解密的。


---原始邮件---
发件人: ***@***.***&gt;
发送时间: 2023年7月23日(周日) 晚上7:59
收件人: ***@***.***&gt;;
抄送: ***@***.***&gt;;
主题: [NXY666/Jsjiemi] 运行时报错 (Issue #95)




 
操作系统
 
Linux
 
Node.js 版本号
 
12.22.9
 
问题详情
 
如图
 
 
目标代码
 readme里的实例
 
&mdash;
